FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

COPY . /app

ENV SPRING_DATASOURCE_URL=jdbc:mysql://mysql-futurevet:3306/db-futurevet
ENV SPRING_DATASOURCE_USERNAME=user-futurevet
ENV SPRING_DATASOURCE_PASSWORD=senha-futurevet

EXPOSE 8080

CMD ["bash", "-c", "mvn clean package -DskipTests && java -jar target/*.jar"]
